### ISSUE TITLE
deploy error on fly

### ISSUE THREAD

**Issue by codeista** [codeista/aw-rpc#4]
2023-02-06T21:41:33.172 app[6e01d22b] syd [info] Starting init (commit: e3cff9e)...
2023-02-06T21:41:33.193 app[6e01d22b] syd [info] Preparing to run: `/cnb/process/web` as 1000
2023-02-06T21:41:33.206 app[6e01d22b] syd [info] 2023/02/06 21:41:33 listening on [fdaa:1:3b09:a7b:b2:6e01:d22b:2]:22 (DNS: [fdaa::3]:53)
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] Traceback (most recent call last):
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] File "/workspace/app.py", line 10, in <module>
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] from flask import redirect, render_template, abort, request
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.10/site-packages/flask/__init__.py", line 3, in <module>
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] from werkzeug.exceptions import abort as abort
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.10/site-packages/werkzeug/__init__.py", line 2, in <module>
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] from .test import Client as Client
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.10/site-packages/werkzeug/test.py", line 30, in <module>
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] from .sansio.multipart import Data
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.10/site-packages/werkzeug/sansio/multipart.py", line 22, in <module>
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] class Preamble(Event):
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.10/site-packages/dataclasses.py", line 950, in wrap
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
2023-02-06T21:41:33.854 app[6e01d22b] syd [info] File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.10/site-packages/dataclasses.py", line 800, in _process_class
2023-02-06T21:41:33.855 app[6e01d22b] syd [info] cls_fields = [_get_field(cls, name, type)
2023-02-06T21:41:33.855 app[6e01d22b] syd [info] File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.10/site-packages/dataclasses.py", line 800, in <listcomp>
2023-02-06T21:41:33.855 app[6e01d22b] syd [info] cls_fields = [_get_field(cls, name, type)
2023-02-06T21:41:33.855 app[6e01d22b] syd [info] File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.10/site-packages/dataclasses.py", line 659, in _get_field
2023-02-06T21:41:33.855 app[6e01d22b] syd [info] if (_is_classvar(a_type, typing)
2023-02-06T21:41:33.855 app[6e01d22b] syd [info] File "/layers/paketo-buildpacks_pip-install/packages/lib/python3.10/site-packages/dataclasses.py", line 550, in _is_classvar
2023-02-06T21:41:33.855 app[6e01d22b] syd [info] return type(a_type) is typing._ClassVar
2023-02-06T21:41:33.855 app[6e01d22b] syd [info] AttributeError: module 'typing' has no attribute '_ClassVar'. Did you mean: 'ClassVar'?
2023-02-06T21:41:34.197 app[6e01d22b] syd [info] Starting clean up.

**Comment by codeista** [comment]
fixed: use python build in toml
